# Generated by Django 4.2.8 on 2024-01-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateTimeField()),
                ('brand', models.CharField(max_length=128)),
                ('type', models.CharField(max_length=128)),
                ('price', models.CharField(max_length=128)),
                ('sales', models.IntegerField()),
            ],
        ),
    ]
