# Generated by Django 4.2.8 on 2024-01-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_cardetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=128)),
                ('volume', models.CharField(max_length=128)),
                ('speed', models.CharField(max_length=128)),
                ('protect', models.CharField(max_length=128)),
                ('length', models.CharField(max_length=128)),
                ('width', models.CharField(max_length=128)),
                ('height', models.CharField(max_length=128)),
                ('wheelbase', models.CharField(max_length=128)),
                ('front_track', models.CharField(max_length=128)),
                ('rear_wheelbase', models.CharField(max_length=128)),
                ('weight', models.CharField(max_length=128)),
                ('doors', models.CharField(max_length=128)),
                ('seats', models.CharField(max_length=128)),
                ('power', models.CharField(max_length=128)),
                ('torque', models.CharField(max_length=128)),
                ('fuel', models.CharField(max_length=128)),
            ],
        ),
    ]
