# Generated by Django 5.0.1 on 2024-01-10 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_alter_asset_id_alter_businessunit_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardetail',
            options={'ordering': ['-update_date']},
        ),
    ]
