# Generated by Django 4.2.8 on 2024-01-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_alter_cardetail_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salesrank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=128)),
                ('price', models.CharField(max_length=128)),
                ('brand', models.CharField(max_length=128)),
                ('sales', models.IntegerField()),
            ],
        ),
    ]
